<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="vMenu.Enhanced.ClientAPI" Version="1.0.7" />
    <PackageVersion Include="vMenu.Enhanced.ServerAPI" Version="1.0.7" />
  </ItemGroup>
</Project>